### ISSUE TITLE
Bug with passing subsectioned string in the configuration "at" function

### ISSUE THREAD

**Issue by bena-nasa** [Goddard-Fortran-Ecosystem/yaFyaml#25]
This is with yafmal version 0.4.1 and intel fortran 19.1.3.304
I have this simple program. I'm finding that when trying to retrieve a key I have to trim the passing to the %at where as if I just take a slice of  of the string without the trim it fails despite the trim slice and the slice without the trim seemingly the same, at least according to the result of the print here. Not clear why a trim is needed but seems like a bug in the compiler perhaps?

```
program yaml_test
use yaFyaml
implicit none
type(Configuration) :: subcfg, config
type(Parser) :: p
type(Filestream) :: fstream
integer :: status,idx
logical :: ll
character(:), allocatable :: key
p = parser('core')
fstream = FileStream("bc_merra2_extdata.yaml")
config = p%load(fstream)
call fstream%close()
key="rules%"//"BC_BIOMASS"
idx = index(key,"%")
! the next 3 lines all evaluate to true when run
write(*,*)"BC_BIOMASS"==key(idx+1:)
write(*,*)"BC_BIOMASS"==trim(key(idx+1:))
write(*,*)key(idx+1:)==trim(key(idx+1:))
subcfg = config%at(trim(key(:idx-1)),trim(key(idx+1:)),rc=status) ! works
subcfg = config%at(key(:idx-1),key(idx+1:),rc=status) ! segfaults
end program yaml_test
```
the input file:
```
data_sets:
  qfed_bc: {tmpl: "ExtData/PIESA/sfc/QFED/v2.4r6/Y%y4/M%m2/qfed2.emis_bc.005.%y4%m2%d2.nc4"}
  ante_bc: {tmpl: "ExtData/AeroCom/sfc/AeroCom.noship_BC_src.sfc.x360_y181_t44.19780703_12z_20210703_12z.nc"}
  ship_bc: {tmpl: "ExtData/MERRA2/sfc/edgar-v41.emis_bc.navigation.x360_y181_t47.19750703T12z_20210703T00z.nc4"}

rules:
  BC_BIOMASS: {file_key: qfed_bc, var: biomass, regrid: CONSERVE, upd_ref_time: "0" ,upd_freq: PT24H, upd_offset: PT12H}
  BC_BIOFUEL: {file_key: "/dev/null"}
  BC_ANTEBC1: {file_key: ante_bc, var: antebc1, regrid: CONSERVE, upd_ref_time: "0" ,upd_freq: PT24H, upd_offset: PT12H}
  BC_ANTEBC2: {file_key: "/dev/null"}
  BC_SHIP: {file_key: ship_bc, var: bc_ship, regrid: CONSERVE, upd_ref_time: "0" ,upd_freq: PT24H, upd_offset: PT12H}
  BC_AVIATION_LTO: {file_key: "/dev/null"}
  BC_AVIATION_CDS: {file_key: "/dev/null"}
  BC_AVIATION_CRS: {file_key: "/dev/null"}
```
and the traceback
```
 T
 T
 T
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
yaml_test.x        0000000000561C5A  Unknown               Unknown  Unknown
libpthread-2.22.s  00002AAAAAFDCC10  Unknown               Unknown  Unknown
yaml_test.x        0000000000467DAC  fy_configurationg         349  Configuration.F90
yaml_test.x        00000000004678AF  fy_configurationg         336  Configuration.F90
yaml_test.x        00000000004656BE  fy_configuration_         282  Configuration.F90
yaml_test.x        0000000000468A67  fy_configuration_         380  Configuration.F90
yaml_test.x        0000000000469C0D  fy_configuration_         428  Configuration.F90
yaml_test.x        0000000000407006  MAIN__                     27  yaml_test.F90
yaml_test.x        0000000000403152  Unknown               Unknown  Unknown
libc-2.22.so       00002AAAAB40D725  __libc_start_main     Unknown  Unknown
yaml_test.x        0000000000403069  Unknown               Unknown  Unknown
```
