### ISSUE TITLE
Possible bug or oversight with list values and indentation

### ISSUE THREAD

**Issue by bena-nasa** [Goddard-Fortran-Ecosystem/yaFyaml#41]
I've been working on a script to generate a yaml input file for a project from the old version in a different format. I ended up creating a python script and creating a dictionary which I dump to a file with the Python yaml modules "dump" function to take a dictionary and emits it as a yaml text.
In my first attempt I generated a Yaml file that looked like this:
```
Version: 3

Enabled:
- geosgcm_prog

Grids:
  PC96x49-DC:
     grid_type: LatLon
     im_world: 360
     jm_world: 180
     lm: 72
     dateline: DE
     pole: PE

Groups:
  geosgcm_prog_group:
    fields:
      AGCM:
        PHIS: {}

Collections:
  geosgcm_prog:
    frequency: '060000'
    groups:
    - geosgcm_prog_group
    output_grid: PC96x49-DC
    template: '%y4%m2%d2_%h2%n2z.nc4'
```
When this was being ingested by Yafyaml however it crashed and spit out this error:
```
illegal token encountered C
```
I stared at the file for quite a while and could not see what was wrong. Finally after much starting and comparing to a file a I knew that worked the only thing I would see is that the yaml file above has keys who have values that are lists that are not indented (the Enable: key for example, same with groups under collections).

So I indented the lists like so
```
Version: 3

Enabled:
  - geosgcm_prog

Grids:
  PC96x49-DC:
     grid_type: LatLon
     im_world: 360
     jm_world: 180
     lm: 72
     dateline: DE
     pole: PE

Groups:
  geosgcm_prog_group:
    fields:
      AGCM:
        PHIS: {}

Collections:
  geosgcm_prog:
    frequency: '060000'
    groups:
      - geosgcm_prog_group
    output_grid: PC96x49-DC
    template: '%y4%m2%d2_%h2%n2z.nc4'
```
and Yafyaml was happy. At least as far as python's yaml implementation was concerned it must think that is valid yaml as that is what it produced via the "dump" function of the yaml library.  So I'm guessing (still looking) that the first is valid Yaml that is not support by Yafyaml?
